#BareLibC -- Copyright (C) 2010 Gergely Gabor Nagy (ngg@ngg.hu) -- see attached LICENSE file

ifndef MAKECONFIG
MAKECONFIG = 1

PROJNAME = barelibc

ifeq "$(BINDIR)" ""
BINDIR = ../../bin
endif

ifeq "$(INCDIR)" ""
INCDIR = ../../include
endif

#.SILENT:
.SUFFIXES:
.SECONDARY:
.DEFAULT_GOAL = all
.SECONDEXPANSION:

AS = yasm
ASFLAGS = -f elf64
CC = gcc
CFLAGS = -m64 -nostdlib -nostdinc -nostartfiles -nodefaultlibs -O3 -ffast-math -mno-red-zone -fpack-struct -ffreestanding -undef -std=c99 -pedantic -Wall -Werror -I $(INCDIR)
LD = ld
LDFLAGS = -T $(BINDIR)/app.ld
AR = ar
ARFLAGS = cr

LIB = $(BINDIR)/lib$(PROJNAME).a

%.o: %.asm
	$(AS) $(ASFLAGS) $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

endif #MAKECONFIG


###
