#BareLibC -- Copyright (C) 2010 Gergely Gabor Nagy (ngg@ngg.hu) -- see attached LICENSE file

HEADERNAME = stdlib
CFILES = abs atoi atol atoll bsearch bsearch_arg div \
_exit exit getenv rand itoa labs ldiv llabs lldiv \
mbstowcs mbtowc memory qsort qsort_arg strtol strtoll \
strtoul strtoull system wctomb
include ../Makefile.tpl

###
