#BareLibC -- Copyright (C) 2010 Gergely Gabor Nagy (ngg@ngg.hu) -- see attached LICENSE file

HEADERNAME = stdlib
CFILES = abs atoi atol atoll bsearch bsearch_arg div \
_exit exit getenv rand itoa labs ldiv llabs lldiv \
mbstowcs mbtowc memory qsort qsort_arg strtol strtoll \
strtoul strtoull system wctomb
DEPFILES_memory = sl_c.h sl_h.h sl_c_adv.h sl_c_simple.h memory_adv.c memory_simple.c
INCCOPY = sl_c.h sl_h.h sl_c_adv.h sl_c_simple.h
include ../Makefile.tpl

###
