#BareLibC -- Copyright (C) 2010 Gergely Gabor Nagy (ngg@ngg.hu) -- see attached LICENSE file

HEADERNAME = stdio
CFILES = fprintf fputc fputs snprintf sprintf vfprintf vsnprintf vsprintf __pformat __stdfd
DEPFILES = __stdio_inner.h

include ../Makefile.tpl

###
