#BareLibC -- Copyright (C) 2010 Gergely Gabor Nagy (ngg@ngg.hu) -- see attached LICENSE file

HEADERNAME = string
CFILES = memchr memcmp memmove memset strerror strcat \
strchr strcmp strcpy strcspn strlen strncat strncmp \
strncpy strpbrk strrchr strspn strstr strtok
include ../Makefile.tpl

###
